import React, {useEffect} from "react";

const Cookie = () => {
    useEffect(() => {
        window.scrollTo(0, 0)
    }, []);
    return (
        <>
            <div className="container">
                <div className="row row--grid">
                    <div className="col-12">
                        <div className="main__title main__title--page">
                            <h1>Cookie Policy</h1>
                            <p>Like many online services, we use cookies to collect information. We may use both session Cookies (which expire once you close your web browser) and persistent Cookies (which stay on your computer until you delete them) to analyse how users interact with our Service, make improvements to our product quality, and provide users with a more personalized experience.</p>
                            <p>Pixel Tag. In addition, we use “Pixel Tags” (also referred to as clear Gifs, Web beacons, or Web bugs). Pixel Tags allow us to analyse how users find our Service, make the Service more useful to you, and tailor your experience with us to meet your particular interests and needs.</p>
                            <p>How We Respond to Do Not Track Signals. Our systems do not currently recognize “do not track” signals or other mechanisms that might enable Users to opt out of tracking on our site.</p>
                            <p>Analytics Services. In addition to the tracking technologies, we place like Cookies and Pixel Tags, other companies may set their own cookies or similar tools when you visit our Service. This includes third-party analytics services (“Analytics Services”) that we engage to help analyse how users use the Service. The information generated by the Cookies or other technologies about your use of our Service (the “Analytics Information”) is transmitted to the Analytics Services. The Analytics Services use Analytics Information to compile reports on user activity, which we may receive on an individual or aggregate basis. We use the information we get from Analytics Services to improve our Service. The Analytics Services may also transfer information to third parties where required to do so by law, or where such third parties process Analytics Information on their behalf. Each Analytics Services’ ability to use and share Analytics Information is restricted by such Analytics Services’ terms of use and privacy policy. By using our Service, you consent to the processing of data about you by Analytics Services in the manner and for the purposes set out above.</p>
                            <p>If you decide at any time that you no longer wish to accept Cookies from our Service for any of the purposes described above, then you can instruct your browser, by changing its settings, to stop accepting Cookies or to prompt you before accepting a Cookie from the websites you visit. Consult your browser’s technical information. If you do not accept Cookies, however, you may not be able to use all portions of the Service or all functionality of the Service.</p>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}
export default Cookie
